### ISSUE TITLE
diag: methods sharing names with struct fields produce confusing diagnostic message

### ISSUE THREAD

**Issue by benstt** [alumina-lang/alumina#118]
Unsure if this is a diagnostic or IR issue.

When lowering calls, we are not handling callable items that share names with identifiers. For example, struct methods called the same as one of their fields get treated as identifiers, thus lowering fails.

To me, this looks like an IR issue, but following the [Language Guide](https://github.com/alumina-lang/alumina/blob/master/docs/lang_guide.md#name-resolution), this may well be expected. If this is intentional, we should improve the error diagnostic to mention these name collisions (which can be confusing).

Example (playground example below):
```bare
struct A {
    field: u32,
}

impl A {
    fn field(self: &A) -> u32 {
        self.field
    }
}

fn main() {
    let a = A { field: 42 };
    println!("a.field={}", a.field());
}
```

Output:
```
error: function or static expected
  --> [program.alu:13:28](https://play.alumina-lang.net/#)
```

This happens in `ir/mono/mod.rs`'s `lower_call`: https://github.com/alumina-lang/alumina/blob/304bf3f4ff1f77739f31f3f7fe8c88c0f5b9e9fb/src/alumina-boot/src/ir/mono/mod.rs#L5067-L5093

## Reproducible Example
https://play.alumina-lang.net/?code=1695451deb28b0f0

The above is a rather silly example (could just use `field` directly), but similar situations may happen (e.g., with a builder struct).

## Compilation Info
Revision: `304bf3f4ff1f77739f31f3f7fe8c88c0f5b9e9fb`

```
304bf3f4 (HEAD -> master, origin/master, origin/HEAD) chore: Add settings for Github Linguist (#117)
```

**Comment by tibordp** [comment]
Fields have precedence over methods in name resolution, so from the behavior perspective, this is expected, but I agree that it deserves a better error message. 

Check out #119 for an improvement.

**Comment by benstt** [comment]
That was quick! Thanks, it's much more clear now.
